# Generated by Django 3.1.4 on 2021-05-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=15)),
                ('documentType', models.CharField(choices=[('N', 'Notes'), ('P', 'PYQ'), ('G', 'Gate PYQ')], max_length=1)),
                ('file_name', models.CharField(max_length=100)),
                ('file_size', models.CharField(max_length=20)),
                ('file_text', models.TextField(max_length=10000000)),
                ('file_location', models.CharField(max_length=100)),
            ],
            bases=(models.Model, dict),
        ),
        migrations.CreateModel(
            name='SubjectToSubjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
    ]
